### ISSUE TITLE
Not connecting non-public IP nodes

### ISSUE THREAD

**Issue by edcorfa** [rundeck-plugins/rundeck-ec2-nodes-plugin#17]
I can run jobs in nodes that have a public IP address, but not to the internal ones. 

Checking on the "Nodes" section, I can see that the user is set as "ec2-user" but the hostname field is empty.

Is there a way to force the connection threw internal IP?

**Comment by stack72** [comment]
I have tested this specific mapping and it works :)

**Comment by dvg06** [comment]
When I add this, I get 2 host name fields - one with private dns and other one is blank. Apparently rundeck is trying to use the blank one, and I end up with below errors. any help please?

Failed: ConfigurationFailure: Hostname must be set to connect to remote node 'i-01addfae'
16:10:05	i-0e638cdf	Failed: ConfigurationFailure: Hostname must be set to connect to remote node 'i-0e638cdf'
16:10:05	i-2335778c	Failed: ConfigurationFailure: Hostname must be set to connect to remote node 'i-2335778c'
16:10:05	i-27ce8e88	Failed: ConfigurationFailure: Hostname must be set to connect to remote node 'i-27ce8e88'
