### ISSUE TITLE
Make AWS access key and secret optional, and use IAM profile instead

### ISSUE THREAD

**Issue by boosh** [rundeck-plugins/rundeck-ec2-nodes-plugin#20]
It would be great if this plugin was updated to make supplying an AWS access key and secret optional, and if they aren't present to automatically use an associated IAM role if present instead.

See how boto works if it's not clear what I mean - it probably just requires updating the AWS SDK I expect.

**Comment by Rajpandi** [comment]
Hi gschueler, Why we r using ec2 plugins in Rundeck? could you please explain? this will help me for knowledge :)
