### ISSUE TITLE
Filter documentation improvement

### ISSUE THREAD

**Issue by Tokynet** [rundeck-plugins/rundeck-ec2-nodes-plugin#21]
The docs should have better examples for the filter options. I was trying to filter my instances by AWS TAGs. Going by the documentation here and AWS I thought the filter should look like:
Filter.1.Name=tag:$MYTAGNAME ; Filter.1.Value.1=$MYTAGVALUE

When in reality it should be:
tag:$MYTAGNAME=$MYTAGVALUE

**Comment by SydOps** [comment]
@gschueler 

I use filter `tag:node_environment=uat` or `tag:node_environment=dev`, got the nodes list.

But if I merge them as "tag:node_environment=uat;tag:node_environment=dev", no node get listed.

Rundeck and ec2-nodes-plugin are all latest version.

**Comment by gschueler** [comment]
@SydOps ok, can you file another issue for that? I think the problem is the query is not using a value list, it is only using a single value, so if you specify the same filter name twice, it is not working

**Comment by SydOps** [comment]
@gschueler 

I am fine with this issue now, I create two resources profiles in one project, one uses filter of `tag:node_environment=uat`, the other uses `tag:node_environment=dev`, I can see all of them now. 

Do you still need me raise a new ticket?

**Comment by gschueler** [comment]
@SydOps sure, i think it is a good feature, saves the need to do multiple API calls
