### ISSUE TITLE
Plugin does not provide a way to concatenate EC2 attributes

### ISSUE THREAD

**Issue by pkr1234** [rundeck-plugins/rundeck-ec2-nodes-plugin#24]
Rundeck only displays the nodename in "matched nodes" of the job. So it is important that the nodename contains all the relevant information to identify a node when running a job.

The default for this plugin is:
nodename.selector=tags/Name,instanceId

There are two problems with this:
1. tags/Name will not be unique in autoscaled instances since the tags are propagated.
2. It uses instanceId only when tags/Name is missing

Therefore, we need a way to make nodename unique which can be done by concatenating the two items - tags/Name + instanceId. Is this possible?

**Comment by gschueler** [comment]
you are right, this was brought up in #10, it's a good feature to add

maybe using `+` char to indicate concatenation

**Comment by pkr1234** [comment]
Thanks Greg,

Please could you let me know when this feature is likely to be implemented?

**Comment by gschueler** [comment]
hi @pkr1234 i don't know, sorry :(

**Comment by upsam** [comment]
this would be extremely useful.

**Comment by aguy** [comment]
+1 I came here looking exactly how to do this.

**Comment by gschueler** [comment]
implemented in https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/pull/58
