### ISSUE TITLE
only show one aws instance 

### ISSUE THREAD

**Issue by SydOps** [rundeck-plugins/rundeck-ec2-nodes-plugin#25]
I installed the latest rundeck (2.4.2) and latest rundeck ec2 nodes plugin. But the rundeck server can only discover 1 aws Node (my match filter is correct), if I stop that one, it shows the next running ec2 instance.

I use rundeck version 1.5.x with ec2 plugin before, have no this issue. 

Then I review ec2 plugin release, seems only support rundeck 1.6 (and lower) and 2.0. Does this mean I have to install old rundeck version to match with ec2 plugin?

Could you please confirm?

**Comment by gschueler** [comment]
do your instances have the same name? Rundeck uses the "name" as the unique identifier.  If you have multiple ec2 instances that resolve to the same Rundeck node "name", they might show up as a single node.  You would have to tweak your mapping configuration for the plugin to change the name value

**Comment by SydOps** [comment]
Good points. I have several instances with same name.  Can I choice to list by instance ID in rundeck, then group (filter match) with name?

Anyway, I will check the configuration again.

**Comment by gschueler** [comment]
yes, see the "nodename.selector" here https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin#mapping-definition

**Comment by SydOps** [comment]
Thanks lot, this issue can be closed.
