### ISSUE TITLE
saved filter appears in other projects

### ISSUE THREAD

**Issue by SydOps** [rundeck-plugins/rundeck-ec2-nodes-plugin#26]
Not sure this is the issue in rundeck or rundeck-ec2-nodes-plugin. 

In AWS system, I have three environments (tags environment=dev/uat/prod), So I create three rundeck projects (dev/uat/prod), each environment has several groups, such as abc1, abc2, etc. So for one aws ec2 instance, the tags will be 
```
Name:  hostname
environment:  [dev|uat|prod]
Group:  [abc1|abc2|abc3]
```

In rundeck dev project, I save the filter (group: abc1), I can see all instances (dev and abc1) in that group, so saved the filter as "dev.abc1"

So I move to uat project, then i found the filter (dev.abc1) is also appeared in project uat, and if I choice it, show the dev instances, that's not right. I shouldn't see any dev instances in uat project.

Could you please help if there are something I can fixe?

My environment:
```
latest rundeck version 2.5
latest ec2 plugin version 1.5
centos 6.5
all instances include rundeck are aws ec2 instances.
```

**Comment by gschueler** [comment]
how was the ec2 plugin set up for each project, did you filter the nodes?

**Comment by SydOps** [comment]
Thanks, @gschueler 

My rundeck instance is aws ec2 instance as well. I put `rundeck-ec2-nodes-plugin-1.5.jar` under `/var/lib/rundeck/libext`

Create dev and uat projects as same way (Add a new Resource Model Source --> AWS EC2 Resources)
```
Filter Params  tag:node_environment=uat or dev
Mapping Params  username.default=ec2-user;hostname.selector=privateIpAddress;tags.selector=tags/group
```

`Mapping params` are same in both projects. Accept default for rest.

**Comment by SydOps** [comment]
@gschueler any updates for this issue?

**Comment by gschueler** [comment]
just had a look at this. it does look like a bug in rundeck. I filed it as https://github.com/rundeck/rundeck/issues/1231

**Comment by SydOps** [comment]
@gschueler 
Thanks for the updates. I will go through rundeck/rundeck#1231 to add my comments.

**Comment by SydOps** [comment]
@gschueler 

I saw the pull request for this issue has been merged to rundeck, that's great.  I start testing with the latest commits, will be back for the result.

**Comment by SydOps** [comment]
@gschueler 

I confirmed the problem has been fixed in new release 2.5.1.

But I am not in the `Bug Reporters` list for this new release.

**Comment by gschueler** [comment]
@SydOps Apologies! It is auto generated from the issue reporters in the rundeck project, but since I ended up creating the issue it didn't have you in the list, sorry.

**Comment by SydOps** [comment]
I should thank to you. I am appreciated that you can work it out in so short time.
