### ISSUE TITLE
import project, but aws ec2 resources setting is gone. 

### ISSUE THREAD

**Issue by SydOps** [rundeck-plugins/rundeck-ec2-nodes-plugin#29]
Hi

I follow the document [Rundeck Backup and Recovery](http://rundeck.org/docs/administration/backup-and-recovery.html) to export the project profile (which generates a jar file)

But when I import it, I found the setting for aws ec2 resources are not restored.

**Comment by gschueler** [comment]
@SydOps that document doesn't mention the project config data, which would have to be copied as well.

**Comment by SydOps** [comment]
Thanks @gschueler . Yes, there is the comments in the end which I missed. The issue can be closed.

    Note that because the archive does not contain the project configuration or resource definitions, you will have to configure those separately for the new or updated project.

But it didn't get the detail on how to backup the `project configuration or resource definitions`
