### ISSUE TITLE
unable to execute a script locally on the server node

### ISSUE THREAD

**Issue by thpham** [rundeck-plugins/rundeck-ec2-nodes-plugin#30]
It appears that ~/var/resourceModelSourceCache/{project_name}/1.aws-ec2.xml which describes EC2 nodes list overrides or doesn't merge nodes defined within resources.xml of a project. That means the localhost node is not described and we are not able to run local scripts.

As improvement, it would be great to have the resulting nodes list,  as a merge of those from the EC2 plugin with those from resources.xml

**Comment by gschueler** [comment]
the order of the Resource Model Sources you define for you project determines the order in which duplicate node definitions get merged.  If you want the local resources.xml to take precedence, put it in a lower position.

**Comment by thpham** [comment]
thanks you ! and sorry it was also a misunderstanding on my side ! everything works as expected !
