### ISSUE TITLE
not working with rundeck 2.6.2-1?

### ISSUE THREAD

**Issue by trmiller** [rundeck-plugins/rundeck-ec2-nodes-plugin#35]
The plugin does not appear to show up when following the installation instructions.  Steps to reproduce:

* Setup rundeck 2.6.2 using [self-contained launcher](http://dl.bintray.com/rundeck/rundeck-maven/rundeck-launcher-2.6.2.jar)
* Download rundeck-ec2-nodes-plugin [from the releases page](https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/releases).  None of the version appear to work, so latest is a good candiate
* Copy jar to $RUNDECK_BASE/libext

Expected behavior
* Navigate to the system configuration -> List Plugins -> Resource Model Sources.  ec2-nodes plugin should be displayed
* Under project configuration -> Simple Configuration -> Resource Model Sources -> Add Source, ec2-nodes should be an option

Current behavior
* Plugin does not show up in list plugins
* Ec2 is not an option under Resource Model Sources
* When configuring manually, an exception is thrown not recognizing the provider type.

**Comment by gschueler** [comment]
can you verify the ownership/permissions of the plugin file are ok (match rundeck server user)? i see the ec2 plugin working in 2.6.2 after copying it to libext directory

**Comment by trmiller** [comment]
Permissions match user running rundeck and same as all other plugins.  No other plugins are installed.   I'm running the server as ec2-user

    -rw-r--r--. 1 ec2-user ec2-user    3908 Dec 18 12:26 rundeck-copyfile-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user     610 Dec 18 12:26 rundeck-ec2-nodes-plugin-1.5.1.jar
    -rw-r--r--. 1 ec2-user ec2-user    2301 Dec 18 12:26 rundeck-flow-control-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user 2761859 Dec 18 12:26 rundeck-git-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user 2546869 Dec 18 12:26 rundeck-jasypt-encryption-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user    6075 Dec 18 12:26 rundeck-job-state-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user    3473 Dec 18 12:26 rundeck-localexec-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user    9527 Dec 18 12:26 rundeck-orchestrator-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user   16139 Dec 18 12:26 rundeck-script-plugin-2.6.2.jar
    -rw-r--r--. 1 ec2-user ec2-user    9534 Dec 18 12:26 rundeck-stub-plugin-2.6.2.jar

**Comment by gschueler** [comment]
File size 610 for the plugin file seems wrong. Try downloading it again?

-- 
Greg

**Comment by trmiller** [comment]
user error - apologies for noise.
