### ISSUE TITLE
some links are dead

### ISSUE THREAD

**Issue by SydOps** [rundeck-plugins/rundeck-ec2-nodes-plugin#39]
1) In page http://rundeck.org/docs/plugins-user-guide/installing.html, below links are dead.

http://rundeck.org/docs/plugins-user-guide/script-plugins.html#stub-plugin
http://rundeck.org/docs/plugins-user-guide/script-plugins.html#script-plugins

But I can find the similar document in other version. 

http://rundeck.org/2.1.1/plugins-user-guide/script-plugins.html

2) in page http://rundeck.org/docs/administration/configuration-file-reference.html , all links to Codehaus website are dead. Because: 

    All Codehaus services have been terminated

3) in page http://rundeck.org/docs/administration/configuration-file-reference.html#project-configuration-storage-settings below links are dea. 

http://rundeck.org/docs/administration/ssh-key-storage.html
http://rundeck.org/docs/administration/ssh-key-storage.html#configuring-storage-plugins
http://rundeck.org/docs/administration/ssh-key-storage.html#configuring-storage-converter-plugins

**Comment by gschueler** [comment]
hi, thanks, i think you should file this in the rundeck project, however, https://github.com/rundeck/rundeck/issues

btw, all of the documentation lives here https://github.com/rundeck/rundeck/tree/development/docs
