### ISSUE TITLE
Filter improvement

### ISSUE THREAD

**Issue by SydOps** [rundeck-plugins/rundeck-ec2-nodes-plugin#41]
As required in #21, I raise this issue.

I use filter `tag:node_environment=uat` or `tag:node_environment=dev`, got the node lists.

But if I merge them as `tag:node_environment=uat;tag:node_environment=dev`, no node got listed.

I'd like to list both uat and dev nodes.

My environment: 
Rundeck and ec2-nodes-plugin are all latest version.
https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/commit/ad48597184b9130cc61bb105159a0bb4570275e8#diff-1e290ac8433d555bce009b162cb869d0L38

**Comment by dabest1** [comment]
I'm also interested in this feature. It would avoid a lot of duplication work.
