### ISSUE TITLE
Node list not populated

### ISSUE THREAD

**Issue by scalp42** [rundeck-plugins/rundeck-ec2-nodes-plugin#42]
Hi there,

Using a fresh install of `Rundeck 2.6.2` and `rundeck-ec2-nodes-plugin-1.5.1.jar` (I also tried master), the node list is not populated at all:

![](https://i.imgur.com/YsHANLh.png)

I can confirm the IAM profile has correct access to ec2:* and used a token as well with full access to test:

![](https://i.imgur.com/O1yZbbd.png)

The xml is pretty much empty on the server:

```
root@noop-i-7d2780a5 /var/lib/rundeck/var/resourceModelSourceCache/antho # ll
total 12K
drwxrwxr-x 2 rundeck rundeck 4.0K Feb 22 23:19 ./
drwxrwxr-x 3 rundeck rundeck 4.0K Feb 22 23:18 ../
-rw-rw-r-- 1 rundeck rundeck   51 Feb 22 23:38 2.aws-ec2.xml

root@noop-i-7d2780a5 /var/lib/rundeck/var/resourceModelSourceCache/antho # cat 2.aws-ec2.xml
<?xml version="1.0" encoding="UTF-8"?>

<project/>
```

Any ideas ? The logs don't show anything unfortunately.

Thanks in advance!

**Comment by scalp42** [comment]
@gschueler confirming also that I configured the resource correctly:

![](https://i.imgur.com/1gKcblz.png)

**Comment by gschueler** [comment]
what ec2 realm are you using?  you might need to set the endpoint

**Comment by scalp42** [comment]
Good catch, using us-west-2, let me try that.

**Comment by scalp42** [comment]
That was totally the endpoint, thanks @gschueler! Closing.
