### ISSUE TITLE
show all hosts from 2 different aws accounts in 1 project

### ISSUE THREAD

**Issue by amitdaniel86-zz** [rundeck-plugins/rundeck-ec2-nodes-plugin#55]
Hi Greg , 

I would like to know if there is an options to get all aws hosts from 2 different account in 1 rundeck project .

For now i have 2 different aws accounts.
1 rundeck project for example called : X-project and use IAM role to access X account
another rundeck project called : Y-project and use access_key & secret_key to access Y account

is there any other options to get all the hosts from X & Y accounts in 1 rundeck project ?

Thanks , 
Amit

**Comment by gschueler** [comment]
you can add 2 ec2 sources for the same project, and configure one with the access_key, and let the other use the IAM profile
