### ISSUE TITLE
Proxy ignored

### ISSUE THREAD

**Issue by zash01** [rundeck-plugins/rundeck-ec2-nodes-plugin#56]
Hi,
I am using the plugin version 1.5.2 
The Proxy is set in the required fields, also set as Java parameters for rundeck and in /etc/environment. The AWS Endpoint is also set correct.
It should be used the Instance IAM-Role to get the Nodes from EC2.
But I get this Exception and the Nodes are not imported
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connect to sts.amazonaws.com:443 timed out

Thanks in advance!

**Comment by opticpow** [comment]
I am also seeing he same behavior. When using IAM keys, accessing the ec2 endpoint uses the configured proxy credentials. However when using an ARN, the call to STS is not honoring the proxy settings.  Using the latest 1.5.5 release.

`2018-01-08 20:23:05,420 [NodeService-SourceLoader67] ERROR com.dtolabs.rundeck.core.common.ProjectNodeSupport - Failed loading resource model source #1 in project bmo-platform-test1, skipping: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to sts.amazonaws.com:443 [sts.amazonaws.com/54.239.29.25] failed: connect timed out`

**Comment by gretel** [comment]
@gschueler could this be merged? it's important for enterprise environments.

**Comment by gretel** [comment]
thanks, but it doesn't change the behaviour for me. can you check on your side? regards
