### ISSUE TITLE
Grafana Cloudwatch Connection error

### ISSUE THREAD

**Issue by TFaraj** [rundeck-plugins/rundeck-ec2-nodes-plugin#59]
Hi,

We have got Grafana installed and configured with AWS/EC2 Cloudwatch Datasource and it is successfully.
However, when we open the Dashboard, it displays all measures with no datapoint.
Below is the error log showing on the server:

 lvl=eror msg="CloudWatch: Failed to assume role%!(EXTRA []interface {}=[AccessDenied: User: arn:aws:iam::xxxxxxxx:user/grafana-user is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxx:role/grafana-role\n\tstatus code: 403, request id: 

Any help would be appreciated

**Comment by gschueler** [comment]
this doesn't sound like a problem with the rundeck ec2 nodes plugin

**Comment by Kasunmadura** [comment]
Any solution for that ?

**Comment by gschueler** [comment]
closing issue: has nothing to do with rundeck ec2 nodes plugin
