### ISSUE TITLE
authenticate using a username password

### ISSUE THREAD

**Issue by sandeepdaggupati** [rundeck-plugins/rundeck-ec2-nodes-plugin#64]
Hi Greg,

Can I use the password stored in the Key Storage to authenticate to the ec2 nodes? 

We would like to setup a rundeck service account on all the ec2 nodes in our environment and use the password stored in the Key Storage to ssh into the nodes instead of private keys.

Thanks,
Sandeep.

**Comment by gschueler** [comment]
yes either configure the project with a default key storage key, or set the `ssh-key-storage-path` attribute on the ec2 nodes.  you can do that in the plugin mapping, e.g.: 

    ssh-key-storage-path.default=keys/ec2/${node.name}.key

**Comment by gschueler** [comment]
also set the auth type to "password":

    ssh-authentication.default=password

**Comment by sandeepdaggupati** [comment]
Thanks Greg. It worked
