### ISSUE TITLE
How to use different username than the default one?

### ISSUE THREAD

**Issue by boyke-triwahyudi** [rundeck-plugins/rundeck-ec2-nodes-plugin#83]
Most of the server I used are using Ubuntu, and I've configured 
`resources.source.2.config.mappingParams=username.default\=ubuntu`

How if I want to connect to a server that needs a different username? eg. ec2-user?

Thanks

**Comment by gschueler** [comment]
you could set the value as an instance Tag in ec2 console, and then define a mapping for the username selector.  If the Tag is not set, it will fallback to the default
