### ISSUE TITLE
Use privatednsname for lookup but IP for ip for ssh ?

### ISSUE THREAD

**Issue by rj-reilly** [rundeck-plugins/rundeck-ec2-nodes-plugin#86]
Hi is there a way to lookup by dns name but connect via IP ? I cannot seem to make this work as the private dnsname is not connecting.

**Comment by gschueler** [comment]
what do you mean by "lookup by dns name"?

**Comment by rreilly-edr** [comment]
sorry so I want to lookup the private dns name but when it connects to use the ipaddress and not the hostname.

**Comment by rreilly-edr** [comment]
I figured this was actually using the correct IP when i used debug mode.
