### ISSUE TITLE
ec2 tags

### ISSUE THREAD

**Issue by jasonparmar26** [rundeck-plugins/rundeck-ec2-nodes-plugin#89]
At the moment i have a list of ec2 nodes, is it possible to pass the ec2 instance tags along to rundeck too so it can be used when using the search box, eg - i can select all ec2 nodes with the tag:
instance tags:
Key: app
Value: broker

Kind regards

Jason

**Comment by jasonparmar26** [comment]
Am i supposed to be adding this: 
resources.source.1.config.mappingParams=tags.selector=tags/Project;tags.selector=tags/Role;tags.selector=tags/Environment

Does not seem to pull the Role or Environment tags

**Comment by gschueler** [comment]
see the [mapping format](https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin#mapping-format) info.

instance tags are different than rundeck tags, so you have to decide how you want to map them.  you can map all of your tags to node attributes:

    # Special attributes selector to map all Tags to attributes
    attributes.selector=tags/*

Or if you want to map individual tags as attributes:

    Role.selector=tags/Role
    Environment.selector=tags/Environment

this would set attributes `Role="myrole" Environment="myenvironment"` on the node, if you have instance tags with those values.

If you want actual rundeck Tags, you can do several things, either set a tag if the value is not empty:

    #format: tag.<name>.selector=<field selector>
    tag.HasRole.selector=tags/Role

Or set a tag if the field matches something

    tag.ProductionEnvironment=tags/Environment=Production


Does this solve your problem?

**Comment by shubamkiran** [comment]
> attributes.selector=tags/*
adding this line in mapping params in GUI will do the need or we have to use it along with default mapping ?

**Comment by shubamkiran** [comment]
> > attributes.selector=tags/*
> > adding this line in mapping params in GUI will do the need or we have to use it along with default mapping ?

ok problem solved 
used 
tags.selector=tags/Environment|tags/Role
instead of attributes
